site_name: Novodi Documentation
site_url: https://docs.novodi.com

nav:
    - Home: 'index.md'
    - 'Idea Management':
      - 'Access' : 'idea_management_access.md'
      - 'Concept' : 'idea_management_concept.md'
      - 'Dashboard' : 'idea_management_dashboard.md'
      - 'Ideas' : 'idea_management_ideas.md'
      - 'Sketches' : 'idea_management_sketches.md'
      - 'Projects' : 'idea_management_projects.md'
      - 'Roles' : 'idea_management_roles.md'
    - Marketplace : 'marketplace.md'

    - About: about.md

theme:
    name: mkdocs
    custom_dir: custom_theme/
